name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
        bundler: default
        bundler-cache: true
    - name: Run Specs
      run: |
        gem install bundler
        bundle install
        bundle exec rubocop --format github
        bundle exec rake spec
    - name: Handle Coverage Results
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        lcov-file: ./coverage/lcov/ruby-simplecov.lcov
        github-token: ${{ secrets.GITHUB_TOKEN }}
